// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	   int repetitions = Integer.parseInt(args[0]);
	   int repetitionsCounter =0;
	   int higherCounter = 0;
	   int lowerCounter = 0;
	   while (repetitionsCounter < repetitions){
		if (Math.random() > 0.5) {
			higherCounter++;
		} else {
			lowerCounter++;
		}
		repetitionsCounter++;
	   }
	   System.out.println("> 0.5: " + higherCounter + " times");
	   System.out.println("<= 0.5: " + lowerCounter + " times");
	   if (lowerCounter != 0){
		double ratio = (double) higherCounter / (double) lowerCounter;
		System.out.println("Ratio: " + ratio);
	   }
	}
}
